"use client";

import CreateNewJobForm from "@/app/components/forms/CreateNewJob";
import { time } from "console";
import { useState } from "react";

// export interface Job {
//   id: number AUTOGENERATED
//   jobId: string; AUTGENERATED
//   title: string; TEXT
//   description: string; TEXT
//   customer: string; DROPDOWN
//   contractor: string | null; DROPDOWN
//   address: string; TEXT
//   status: JobStatus; AUTOMATIC
//   priority: JobPriority; DROPDOWN
//   payType: PayType | null; RADIO
//   hoursWorked: number | null;
//   scheduledDate: string | null; DATE
//   scheduledTime: string | null; DATE/TIME
//   createdBy: string; AUTOMATIC or DROPDOWN???
//   createdDate: string; AUTOMATIC

const CreateNewJob = () => {
  const [title, setTitle] = useState("");
  const [descrition, setDescription] = useState("");
  const [customer, setCustomer] = useState("");
  const [contractor, setContractor] = useState("");
  const [address, setAddress] = useState("");
  const [status, setStatus] = useState("open");
  const [priority, setPriority] = useState("");
  const [payType, setPayType] = useState("");
  const [scheduledDate, setScheduledDate] = useState("");
  const [scheduledTime, setScheculedTime] = useState("");
  const [createdBy, setCreatedBy] = useState(() => new Date());
  const [createdDate, setCreatedTime] = useState("");

  return (
    <div>
      <CreateNewJobForm />
    </div>
  );
};

export default CreateNewJob;
